#
# Copyright (c) 2024 Benetti Engineering sas
# Author: Giulio Benetti <giulio.benetti@benettiengineering.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y += clk_rk3562.o
obj-y += rk3562.o
obj-y += syscon_rk3562.o
